name: scan
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        name: checkout code
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go version        
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      - run: java -version
      - name: build frontend
        run: |
          cd frontend && npm install
      - name: Synopsys Detect
        uses: blackducksoftware/github-action@2.0.1
        env:
          SYNOPSYS_SKIP_PHONE_HOME: true
        with:
          args: |
           '--blackduck.url="https://bdscan.daimler.com/api/projects/f53ce07f-f6c8-49de-97f9-449d02515d42"  \
           --detect.project.name="Training_PCS" \
           --blackduck.api.token="NTM4Y2IyYWItYmQxYy00NzVjLTgzZjYtNjY1NzFhOGZhZjBhOjNlMjNjYzY4LTc2ZjctNGM1Zi05NjU0LWU3ZjJlYWU5ZmUwYg==" \
           --detect.excluded.detector.types=GIT \
           --detect.project.version.name="1.3-beta" \
           --detect.detector.search.depth=3 \
           --detect.blackduck.signature.scanner.exclusion.name.pattern=.git,node_modules \
           '
#       - name: Commit changes
#         uses: EndBug/add-and-commit@v4
#         with:
#           author_name: Scan Bot
#           author_email: scan@bot
#           message: "new scan report"
#           add: "*.txt"
#           ref: 'release'
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}           
           

# --detect.notices.report=true \
# --detect.detector.search.depth=3 \
# --detect.npm.include.dev.dependencies=false \
# --detect.policy.check.fail.on.severities=CRITICAL \

